<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
load("D:/Predictive Analytics/Udacity/Predictive Analytics for Business/Project 3/cleaned/training_data_set.csv")
```


```{r}
load("D:/Predictive Analytics/Udacity/Predictive Analytics for Business/Project 3/cleaned/training_data_set.csv")
```



```{r}
scatterplot(total_sales~Households.with.Under.18, regLine=FALSE, 
  smooth=FALSE, boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Households.with.Under.18, regLine=TRUE, 
  smooth=list(span=0.5, spread=FALSE), boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Households.with.Under.18, regLine=TRUE, 
  smooth=FALSE, boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Households.with.Under.18, regLine=TRUE, 
  smooth=FALSE, boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~land_area, regLine=TRUE, smooth=FALSE, 
  boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Population.Density, regLine=TRUE, smooth=FALSE, 
  boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Total.Families, regLine=TRUE, smooth=FALSE, 
  boxplots=FALSE, data=training_data_set)
```

```{r}
scatterplot(total_sales~Households.with.Under.18, regLine=TRUE, 
  smooth=FALSE, boxplots=FALSE, data=training_data_set)
```

```{r}
{scatterplot(total_sales~Households.with.Under.18, regLine=TRUE,
} {smooth=FALSE, boxplots=FALSE, data=training_data_set)
}```


